/**
 * Route merging for the app router.
 *
 * Precedence, highest first:
 *   1. `customRedirects`  (custom-routes.js)
 *   2. `redirects`        (additional-routes.js — template)
 *   3. `customRoutes`     (custom-routes.js)
 *   4. `routes`           (additional-routes.js — template)
 *   5. file-based pages   (src/pages, generated by unplugin-vue-router)
 *
 * Kept in its own module (free of virtual/vite-only imports) so the behaviour
 * can be reasoned about and tested on its own.
 */

/**
 * Builds a predicate that reports whether a route is superseded by one of
 * `overrides`, matching on `name` or on `path`. Removing those duplicates is
 * what stops vue-router from registering two records under the same name.
 *
 * ℹ️ Compares top level records only. To override a nested route, redeclare
 * its parent route in full.
 *
 * @param {Array<{ name?: string | symbol, path?: string }>} overrides
 * @returns {(route: { name?: string | symbol, path?: string }) => boolean}
 */
export function createOverrideFilter(overrides) {
  const names = new Set(overrides.map(route => route.name).filter(Boolean))
  const paths = new Set(overrides.map(route => route.path).filter(Boolean))
  
  return route => (!!route.name && names.has(route.name)) || (!!route.path && paths.has(route.path))
}

/**
 * @param {object} options
 * @param {Array} options.pages            Auto generated file-based routes.
 * @param {Array} options.templateRoutes   `routes` from additional-routes.js
 * @param {Array} options.templateRedirects `redirects` from additional-routes.js
 * @param {Array} options.customRoutes     `customRoutes` from custom-routes.js
 * @param {Array} options.customRedirects  `customRedirects` from custom-routes.js
 * @param {(route: object) => object} options.applyLayouts Wraps a route in its layout.
 * @returns {Array} Final route records handed to vue-router.
 */
export function mergeRoutes({
  pages = [],
  templateRoutes = [],
  templateRedirects = [],
  customRoutes = [],
  customRedirects = [],
  applyLayouts = route => route,
}) {
  const isOverridden = createOverrideFilter(customRoutes)
  const isRedirected = createOverrideFilter(customRedirects)
  const keep = route => !isOverridden(route) && !isRedirected(route)
  
  return [
    // Redirects go first: on an equally specific path match, the record
    // registered earliest wins.
    ...customRedirects,
    ...templateRedirects.filter(route => !isRedirected(route)),
    ...[
      ...pages.filter(keep),
      ...templateRoutes.filter(keep),
      ...customRoutes,
    ].map(route => applyLayouts(route)),
  ]
}
